name: Build Android APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      ANDROID_HOME: /tmp/android-sdk
      PATH: /tmp/android-sdk/cmdline-tools/latest/bin:/tmp/android-sdk/platform-tools:~/.local/bin:${{ env.PATH }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y openjdk-11-jdk unzip wget python3-pip python3-setuptools git

      - name: Install Buildozer
        run: |
          python3 -m pip install --user --upgrade buildozer

      - name: Download and install Android cmdline-tools
        run: |
          mkdir -p $ANDROID_HOME/cmdline-tools
          cd $ANDROID_HOME/cmdline-tools
          wget https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip -O cmdline-tools.zip
          unzip -q cmdline-tools.zip
          rm cmdline-tools.zip
          # The zip creates a cmdline-tools folder, move it to latest/
          rm -rf $ANDROID_HOME/cmdline-tools/latest
          mv cmdline-tools $ANDROID_HOME/cmdline-tools/latest
        shell: bash

      - name: Accept Android SDK licenses and update SDK
        run: |
          yes | sdkmanager --sdk_root=$ANDROID_HOME --licenses
          sdkmanager --sdk_root=$ANDROID_HOME --update

      - name: Install SDK packages needed for build
        run: |
          sdkmanager --sdk_root=$ANDROID_HOME "platform-tools" "platforms;android-33" "build-tools;33.0.2"

      - name: Run Buildozer to build APK
        run: |
          ~/.local/bin/buildozer android debug
