name: Build Android APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ubuntu:22.04

    env:
      ANDROID_HOME: /opt/android-sdk
      PATH: /opt/android-sdk/cmdline-tools/latest/bin:/opt/android-sdk/platform-tools:/home/builder/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

    steps:
      - name: Create non-root user
        run: |
          useradd -m builder
          echo "builder ALL=(ALL) NOPASSWD:ALL" >> /etc/sudoers

      - name: Install dependencies (as root)
        run: |
          apt-get update
          DEBIAN_FRONTEND=noninteractive apt-get install -y \
            openjdk-11-jdk unzip wget git python3-pip python3-setuptools \
            cython3 build-essential zip zlib1g-dev libncurses-dev \
            libffi-dev bash curl coreutils sudo

      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Setup Buildozer and Android SDK and build APK as builder user
        run: |
          sudo -u builder bash <<'EOF'
          set -e
          export HOME=/home/builder
          export ANDROID_HOME=/opt/android-sdk
          export PATH=$ANDROID_HOME/cmdline-tools/latest/bin:$ANDROID_HOME/platform-tools:$HOME/.local/bin:$PATH
          export BUILD_DEBUG_ROOT_IGNORE=1

          # Upgrade pip and install buildozer
          python3 -m pip install --upgrade --user pip setuptools wheel
          python3 -m pip install --user buildozer

          # Install Android cmdline tools if not already present
          if [ ! -d "$ANDROID_HOME/cmdline-tools/latest" ]; then
            mkdir -p $ANDROID_HOME/cmdline-tools
            cd $ANDROID_HOME/cmdline-tools
            wget https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip -O cmdline-tools.zip
            unzip -q cmdline-tools.zip
            rm cmdline-tools.zip
            mv cmdline-tools $ANDROID_HOME/cmdline-tools/latest
          fi

          # Accept licenses
          yes | sdkmanager --sdk_root=$ANDROID_HOME --licenses || true

          # Install required SDK packages
          sdkmanager --sdk_root=$ANDROID_HOME "platform-tools" "platforms;android-33" "build-tools;33.0.2"

          # Go to repo directory
          cd $GITHUB_WORKSPACE

          # Run Buildozer to build APK
          ~/.local/bin/buildozer android debug
          EOF

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-debug.apk
          path: |
            **/bin/*.apk
