name: Build Android APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ubuntu:22.04

    env:
      ANDROID_HOME: /opt/android-sdk
      PATH: /opt/android-sdk/cmdline-tools/latest/bin:/opt/android-sdk/platform-tools:/root/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

    steps:
      - name: Install system dependencies
        run: |
          apt-get update
          DEBIAN_FRONTEND=noninteractive apt-get install -y \
            openjdk-11-jdk \
            unzip \
            wget \
            git \
            python3-pip \
            python3-setuptools \
            cython3 \
            build-essential \
            zip \
            zlib1g-dev \
            libncurses-dev \
            libffi-dev \
            bash \
            curl \
            coreutils

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Buildozer
        run: |
          python3 -m pip install --upgrade pip setuptools wheel
          python3 -m pip install --user buildozer

      - name: Download and install Android cmdline-tools
        run: |
          mkdir -p $ANDROID_HOME/cmdline-tools
          cd $ANDROID_HOME/cmdline-tools
          wget https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip -O cmdline-tools.zip
          unzip -q cmdline-tools.zip
          rm cmdline-tools.zip
          mv cmdline-tools $ANDROID_HOME/cmdline-tools/latest

      - name: Accept SDK licenses
        run: |
          yes | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --sdk_root=$ANDROID_HOME --licenses || true

      - name: Install SDK packages
        run: |
          $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --sdk_root=$ANDROID_HOME \
            "platform-tools" "platforms;android-33" "build-tools;33.0.2"

      - name: Build APK
        run: |
          ~/.local/bin/buildozer android debug
