name: Build Android APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      ANDROID_HOME: /tmp/android-sdk
      PATH: /tmp/android-sdk/cmdline-tools/latest/bin:/tmp/android-sdk/platform-tools:/home/runner/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install system dependencies including coreutils and dash
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            openjdk-11-jdk \
            unzip \
            wget \
            python3-pip \
            python3-setuptools \
            git \
            cython3 \
            build-essential \
            zip \
            zlib1g-dev \
            libncurses-dev \
            libstdc++6 \
            libffi-dev \
            coreutils \
            dash

      - name: Fix /bin/sh symlink to dash
        run: |
          sudo ln -sf /bin/dash /bin/sh

      - name: Upgrade pip and install Buildozer
        run: |
          python3 -m pip install --upgrade pip setuptools wheel
          python3 -m pip install --user --upgrade buildozer

      - name: Download and install Android cmdline-tools
        run: |
          mkdir -p $ANDROID_HOME/cmdline-tools
          cd $ANDROID_HOME/cmdline-tools
          wget https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip -O cmdline-tools.zip
          unzip -q cmdline-tools.zip
          rm cmdline-tools.zip
          rm -rf $ANDROID_HOME/cmdline-tools/latest
          mv cmdline-tools $ANDROID_HOME/cmdline-tools/latest
        shell: bash

      - name: Accept Android SDK licenses
        env:
          PATH: ${{ env.ANDROID_HOME }}/cmdline-tools/latest/bin:$PATH
        shell: bash
        run: |
          yes | sdkmanager --sdk_root=$ANDROID_HOME --licenses

      - name: Install required Android SDK packages
        env:
          PATH: ${{ env.ANDROID_HOME }}/cmdline-tools/latest/bin:$ANDROID_HOME/platform-tools:$PATH
        shell: bash
        run: |
          sdkmanager --sdk_root=$ANDROID_HOME "platform-tools" "platforms;android-33" "build-tools;33.0.2"

      - name: Verify essential tools installation
        run: |
          git --version
          cython3 --version
          java -version
          sdkmanager --version

      - name: Build APK (debug)
        env:
          PATH: /home/runner/.local/bin:$PATH
          ANDROID_HOME: ${{ env.ANDROID_HOME }}
        shell: bash
        run: |
          ~/.local/bin/buildozer android debug
