name: Build Android APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      ANDROID_HOME: /tmp/android-sdk
      PATH: /tmp/android-sdk/cmdline-tools/latest/bin:/tmp/android-sdk/platform-tools:/home/runner/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install system dependencies
        shell: bash
        run: |
          sudo apt-get update
          sudo apt-get install -y openjdk-11-jdk unzip wget python3-pip python3-setuptools git cython3 build-essential zip zlib1g-dev libncurses-dev libffi-dev coreutils bash

      - name: Fix /bin/sh symlink to bash
        shell: bash
        run: |
          if [ -f /bin/sh ]; then sudo rm /bin/sh; fi
          sudo ln -s /bin/bash /bin/sh

      - name: Upgrade pip and install Buildozer
        shell: bash
        run: |
          python3 -m pip install --upgrade pip setuptools wheel
          python3 -m pip install --user --upgrade buildozer

      - name: Download and install Android cmdline-tools
        shell: bash
        run: |
          mkdir -p $ANDROID_HOME/cmdline-tools
          cd $ANDROID_HOME/cmdline-tools
          wget https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip -O cmdline-tools.zip
          unzip -q cmdline-tools.zip
          rm cmdline-tools.zip
          rm -rf $ANDROID_HOME/cmdline-tools/latest
          mv cmdline-tools $ANDROID_HOME/cmdline-tools/latest

      - name: Accept Android SDK licenses
        shell: bash
        env:
          PATH: ${{ env.ANDROID_HOME }}/cmdline-tools/latest/bin:$PATH
          ANDROID_HOME: ${{ env.ANDROID_HOME }}
        run: |
          yes_cmd() { for i in {1..25}; do echo y; done; }
          yes_cmd | sdkmanager --sdk_root=$ANDROID_HOME --licenses || true

      - name: Install SDK packages
        shell: bash
        env:
          PATH: ${{ env.ANDROID_HOME }}/cmdline-tools/latest/bin:$ANDROID_HOME/platform-tools:$PATH
          ANDROID_HOME: ${{ env.ANDROID_HOME }}
        run: |
          sdkmanager --sdk_root=$ANDROID_HOME "platform-tools" "platforms;android-33" "build-tools;33.0.2"

      - name: Verify tools installed
        shell: bash
        run: |
          git --version
          cython3 --version
          java -version
          sdkmanager --version

      - name: Build APK with Buildozer
        shell: bash
        env:
          PATH: /home/runner/.local/bin:$PATH
          ANDROID_HOME: ${{ env.ANDROID_HOME }}
        run: |
          buildozer android debug
