name: Build Android APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ubuntu:22.04

    env:
      ANDROID_HOME: /opt/android-sdk
      PATH: /opt/android-sdk/cmdline-tools/latest/bin:/opt/android-sdk/platform-tools:/root/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

    steps:
      - name: Install dependencies
        run: |
          apt-get update
          DEBIAN_FRONTEND=noninteractive apt-get install -y \
            openjdk-11-jdk unzip wget git python3-pip python3-setuptools \
            cython3 build-essential zip zlib1g-dev libncurses-dev \
            libffi-dev bash curl coreutils sudo

      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Setup Buildozer and Android SDK
        run: |
          set -e
          export ANDROID_HOME=/opt/android-sdk
          export PATH=$ANDROID_HOME/cmdline-tools/latest/bin:$ANDROID_HOME/platform-tools:$HOME/.local/bin:$PATH
          export BUILD_DEBUG_ROOT_IGNORE=1

          # Install Buildozer
          python3 -m pip install --upgrade pip setuptools wheel
          python3 -m pip install --user buildozer

          # Download and install Android cmdline-tools
          mkdir -p $ANDROID_HOME/cmdline-tools
          cd $ANDROID_HOME/cmdline-tools
          wget https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip -O cmdline-tools.zip
          unzip -q cmdline-tools.zip
          rm cmdline-tools.zip
          rm -rf $ANDROID_HOME/cmdline-tools/latest
          mv cmdline-tools $ANDROID_HOME/cmdline-tools/latest

          # Accept licenses
          yes | sdkmanager --sdk_root=$ANDROID_HOME --licenses || true

          # Install required Android packages
          sdkmanager --sdk_root=$ANDROID_HOME "platform-tools" "platforms;android-33" "build-tools;33.0.2"

          # Back to project directory and build
          cd $GITHUB_WORKSPACE
          ~/.local/bin/buildozer android debug

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-debug.apk
          path: '**/bin/*.apk'
