name: Build Android APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      ANDROID_HOME: /tmp/android-sdk

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install system dependencies including cython3
        run: |
          sudo apt-get update
          sudo apt-get install -y openjdk-11-jdk unzip wget python3-pip python3-setuptools git cython3

      - name: Install Buildozer only
        run: python3 -m pip install --user --upgrade buildozer

      - name: Download and install Android cmdline-tools
        run: |
          mkdir -p $ANDROID_HOME/cmdline-tools
          cd $ANDROID_HOME/cmdline-tools
          wget https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip -O cmdline-tools.zip
          unzip -q cmdline-tools.zip
          rm cmdline-tools.zip
          rm -rf $ANDROID_HOME/cmdline-tools/latest
          mv cmdline-tools $ANDROID_HOME/cmdline-tools/latest
        shell: bash

      - name: Accept Android SDK licenses and update SDK
        env:
          PATH: ${{ env.ANDROID_HOME }}/cmdline-tools/latest/bin:${{ env.ANDROID_HOME }}/platform-tools:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:~/.local/bin
        run: |
          yes | sdkmanager --sdk_root=$ANDROID_HOME --licenses
          sdkmanager --sdk_root=$ANDROID_HOME --update

      - name: Install SDK packages needed for build
        env:
          PATH: ${{ env.ANDROID_HOME }}/cmdline-tools/latest/bin:${{ env.ANDROID_HOME }}/platform-tools:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:~/.local/bin
        run: |
          sdkmanager --sdk_root=$ANDROID_HOME "platform-tools" "platforms;android-33" "build-tools;33.0.2"

      - name: Verify git and cython availability
        run: |
          which git
          git --version
          which cython3
          cython3 --version

      - name: Run Buildozer to build APK
        env:
          PATH: /usr/bin:~/.local/bin:$PATH
        run: ~/.local/bin/buildozer android debug
