name: Build APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      ANDROIDSDK: /usr/local/lib/android/sdk
      ANDROIDNDK: /usr/local/lib/android/sdk/ndk/27.2.12479018
      ANDROID_HOME: /usr/local/lib/android/sdk
      ANDROID_SDK_ROOT: /usr/local/lib/android/sdk
      ANDROID_NDK_HOME: /usr/local/lib/android/sdk/ndk/27.2.12479018

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install buildozer cython

      - name: Clean buildozer's auto-downloaded SDK/NDK
        run: |
          rm -rf ~/.buildozer/android/platform/android-sdk
          rm -rf ~/.buildozer/android/platform/android-ndk-*

      - name: Build APK
        run: |
          buildozer android debug
